Fix exception caused by old swingx version
Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: cannot add to layout: unknown
constraint: LEFT
        at
java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:463)
        at
java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:424)
        at java.awt.Container.addImpl(Container.java:1127)
        at java.awt.Container.add(Container.java:973)
        at
org.jdesktop.swingx.prompt.BuddySupport.addToComponentHierarchy(BuddySup
port.java:72)
        at
org.jdesktop.swingx.prompt.BuddySupport.ensureBuddiesAreInComponentHiera
rchy(BuddySupport.java:139)
        at
org.jdesktop.swingx.plaf.TextUIWrapper$DefaultWrapper.replaceUIIfNeeded(
TextUIWrapper.java:163)
        at
org.jdesktop.swingx.plaf.TextUIWrapper.install(TextUIWrapper.java:49)
        at
org.jdesktop.swingx.JXSearchField.setUseNativeSearchFieldIfPossible(JXSe
archField.java:528)
        at
org.jdesktop.swingx.JXSearchField.<init>(JXSearchField.java:178)
        at
org.jdesktop.swingx.JXSearchField.<init>(JXSearchField.java:166)
        at mediathek.gui.ToolBar.startupFilme(ToolBar.java:147)
        at mediathek.gui.ToolBar.startup(ToolBar.java:107)
        at mediathek.gui.ToolBar.<init>(ToolBar.java:89)
        at mediathek.gui.GuiFilme.<init>(GuiFilme.java:115)
        at mediathek.MediathekGui.initTabs(MediathekGui.java:459)
        at mediathek.MediathekGui.init(MediathekGui.java:402)
        at mediathek.MediathekGui.<init>(MediathekGui.java:242)
        at mediathek.mac.MediathekGuiMac.<init>(MediathekGuiMac.java:30)
        at mediathek.Main.lambda$main$1(Main.java:210)
        at
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPriv
ilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.
java:201)
        at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.jav
a:116)
        at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.
java:105)
        at
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)